export type EnglishFlashcard = {
  id: string;
  deck: "anime" | "cs" | "gym" | "aws" | "reselling";
  level: "A2" | "B1";
  front: string;
  meaningEs: string;
  phrase: string;
  prompt: string;
  idealAnswer: string;
  hint: string;
};

export const ENGLISH_FLASHCARDS: EnglishFlashcard[] = [
  {
    id: "anime-1",
    deck: "anime",
    level: "A2",
    front: "main character",
    meaningEs: "personaje principal",
    phrase: "The main character gets stronger after every fight.",
    prompt: "Describe your favorite anime main character in one English sentence.",
    idealAnswer: "My favorite main character is disciplined, loyal, and always keeps improving.",
    hint: "Use: My favorite main character is... because...",
  },
  {
    id: "anime-2",
    deck: "anime",
    level: "A2",
    front: "training arc",
    meaningEs: "arco de entrenamiento",
    phrase: "This week is my training arc for English and CS.",
    prompt: "Say what you are training this week.",
    idealAnswer: "This week I am training my English, AWS, and programming skills.",
    hint: "Use: This week I am training...",
  },
  {
    id: "anime-3",
    deck: "anime",
    level: "B1",
    front: "plot twist",
    meaningEs: "giro inesperado de la historia",
    phrase: "The plot twist changed the whole story.",
    prompt: "Explain a plot twist without naming spoilers.",
    idealAnswer: "The plot twist revealed that the enemy was connected to the hero's past.",
    hint: "Use past tense: revealed / changed / explained.",
  },
  {
    id: "anime-4",
    deck: "anime",
    level: "A2",
    front: "villain",
    meaningEs: "villano",
    phrase: "A good villain has clear motivation.",
    prompt: "What makes a villain interesting?",
    idealAnswer: "A villain is interesting when his motivation is understandable.",
    hint: "Use: A villain is interesting when...",
  },
  {
    id: "anime-5",
    deck: "anime",
    level: "B1",
    front: "character development",
    meaningEs: "desarrollo de personaje",
    phrase: "Character development makes the story feel real.",
    prompt: "Compare a weak character at the beginning and later.",
    idealAnswer: "At the beginning he is insecure, but later he becomes confident and reliable.",
    hint: "Use: At the beginning..., but later...",
  },
  {
    id: "cs-1",
    deck: "cs",
    level: "A2",
    front: "function",
    meaningEs: "función",
    phrase: "A function takes input and returns output.",
    prompt: "Explain what a function does.",
    idealAnswer: "A function takes an input, processes it, and returns an output.",
    hint: "Use: takes / processes / returns.",
  },
  {
    id: "cs-2",
    deck: "cs",
    level: "B1",
    front: "bug",
    meaningEs: "error en el código",
    phrase: "I found a bug in the validation logic.",
    prompt: "Explain a bug you fixed recently or could fix.",
    idealAnswer: "I fixed a bug where the app showed the wrong date after 7 PM.",
    hint: "Use: I fixed a bug where...",
  },
  {
    id: "cs-3",
    deck: "cs",
    level: "B1",
    front: "debug",
    meaningEs: "depurar / encontrar errores",
    phrase: "I need to debug this API route.",
    prompt: "Say what you need to debug today.",
    idealAnswer: "I need to debug the English flashcard API and check the build logs.",
    hint: "Use: I need to debug... and check...",
  },
  {
    id: "cs-4",
    deck: "cs",
    level: "A2",
    front: "deploy",
    meaningEs: "desplegar / publicar",
    phrase: "I deployed the app with a Cloudflare tunnel.",
    prompt: "Say where the app is deployed.",
    idealAnswer: "The app is deployed on my Fedora server and exposed with a Cloudflare tunnel.",
    hint: "Use passive voice: is deployed / is exposed.",
  },
  {
    id: "cs-5",
    deck: "cs",
    level: "B1",
    front: "design recipe",
    meaningEs: "receta de diseño",
    phrase: "The design recipe helps me solve problems step by step.",
    prompt: "Explain why a design recipe is useful.",
    idealAnswer: "A design recipe is useful because it turns a vague problem into clear steps.",
    hint: "Use: useful because...",
  },
  {
    id: "aws-1",
    deck: "aws",
    level: "A2",
    front: "availability zone",
    meaningEs: "zona de disponibilidad",
    phrase: "An availability zone is an isolated data center area.",
    prompt: "Explain availability zone in simple English.",
    idealAnswer: "An availability zone is a separate place where AWS runs servers.",
    hint: "Use: is a separate place where...",
  },
  {
    id: "aws-2",
    deck: "aws",
    level: "B1",
    front: "scalable",
    meaningEs: "escalable",
    phrase: "A scalable system can handle more users.",
    prompt: "Why should an app be scalable?",
    idealAnswer: "An app should be scalable so it can handle more traffic without breaking.",
    hint: "Use: so it can... without...",
  },
  {
    id: "aws-3",
    deck: "aws",
    level: "B1",
    front: "fault tolerant",
    meaningEs: "tolerante a fallos",
    phrase: "A fault tolerant system keeps working when one part fails.",
    prompt: "Explain fault tolerance with AWS.",
    idealAnswer: "A fault tolerant AWS app keeps working even if one instance or zone fails.",
    hint: "Use: keeps working even if...",
  },
  {
    id: "aws-4",
    deck: "aws",
    level: "A2",
    front: "storage bucket",
    meaningEs: "bucket de almacenamiento",
    phrase: "S3 stores files in storage buckets.",
    prompt: "What can you store in an S3 bucket?",
    idealAnswer: "I can store images, backups, videos, and static website files in an S3 bucket.",
    hint: "Use: I can store...",
  },
  {
    id: "gym-1",
    deck: "gym",
    level: "A2",
    front: "workout",
    meaningEs: "entrenamiento",
    phrase: "Today I have a chest and back workout.",
    prompt: "Describe today's workout.",
    idealAnswer: "Today I have a torso workout after work.",
    hint: "Use: Today I have... after work.",
  },
  {
    id: "gym-2",
    deck: "gym",
    level: "B1",
    front: "calorie deficit",
    meaningEs: "déficit calórico",
    phrase: "A calorie deficit helps me cut weight slowly.",
    prompt: "Explain your cutting goal in English.",
    idealAnswer: "My goal is to stay in a calorie deficit while keeping my strength in the gym.",
    hint: "Use: My goal is to... while...",
  },
  {
    id: "gym-3",
    deck: "gym",
    level: "A2",
    front: "discipline",
    meaningEs: "disciplina",
    phrase: "Discipline beats motivation when I am tired.",
    prompt: "Say why discipline matters.",
    idealAnswer: "Discipline matters because I need to study and train even when I am tired.",
    hint: "Use: matters because... even when...",
  },
  {
    id: "resell-1",
    deck: "reselling",
    level: "A2",
    front: "used laptop",
    meaningEs: "laptop usada",
    phrase: "I buy used workstation laptops under two hundred dollars.",
    prompt: "Say what kind of laptops you buy.",
    idealAnswer: "I buy used Dell Precision and HP ZBook laptops when the price is low.",
    hint: "Use: I buy used... when...",
  },
  {
    id: "resell-2",
    deck: "reselling",
    level: "B1",
    front: "profit margin",
    meaningEs: "margen de ganancia",
    phrase: "The profit margin depends on shipping, taxes, and repairs.",
    prompt: "Explain what affects your profit margin.",
    idealAnswer: "My profit margin depends on the purchase price, shipping cost, import taxes, and local demand.",
    hint: "Use: depends on...",
  },
  {
    id: "resell-3",
    deck: "reselling",
    level: "B1",
    front: "condition",
    meaningEs: "estado físico/funcional",
    phrase: "The laptop condition is more important than the photos.",
    prompt: "Ask a seller about laptop condition.",
    idealAnswer: "Can you confirm if the laptop turns on, charges correctly, and has no BIOS password?",
    hint: "Use: Can you confirm if...?",
  },
];
